services:
  postgres:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=bd_carrito_compras'
      - 'POSTGRES_PASSWORD=CarritoCompra*'
      - 'POSTGRES_USER=carrito_compra'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shopping_cart"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
