server:
  port: 8085

spring:
  application:
    #name: PharmaCare+
    name: pharma-care
  datasource:
    url: jdbc:postgresql://localhost:5433/bd_carrito_compras
    username: pharma_care
    password: CarritoCompra123*
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKeyForCitaSaludApplicationThatShouldBeAtLeast256BitsLong}
  expiration: 86400000
