spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bd_carrito_compras
    username: carrito_compra
    password: CarritoCompra*
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect